-- =============================================================================
-- Webcore CMS — Phase 4 blog seed
-- =============================================================================
-- Blog posts are managed via the Supabase admin interface, not seeded here.
-- The two placeholder posts (generative-engine-optimization-2026 and
-- headless-commerce-vs-shopify-2026) were removed because they returned 404
-- and were generating crawl errors from the client-side fallback.
-- =============================================================================
