/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesWebDevelopmentRouteImport } from './routes/services.web-development'
import { Route as ServicesSoftwareDevelopmentRouteImport } from './routes/services.software-development'
import { Route as ServicesSeoGeoRouteImport } from './routes/services.seo-geo'
import { Route as ServicesItConsultationRouteImport } from './routes/services.it-consultation'
import { Route as ServicesGraphicDesignRouteImport } from './routes/services.graphic-design'
import { Route as ServicesCmsDevelopmentRouteImport } from './routes/services.cms-development'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebDevelopmentRoute = ServicesWebDevelopmentRouteImport.update({
  id: '/services/web-development',
  path: '/services/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSoftwareDevelopmentRoute =
  ServicesSoftwareDevelopmentRouteImport.update({
    id: '/services/software-development',
    path: '/services/software-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSeoGeoRoute = ServicesSeoGeoRouteImport.update({
  id: '/services/seo-geo',
  path: '/services/seo-geo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesItConsultationRoute = ServicesItConsultationRouteImport.update({
  id: '/services/it-consultation',
  path: '/services/it-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGraphicDesignRoute = ServicesGraphicDesignRouteImport.update({
  id: '/services/graphic-design',
  path: '/services/graphic-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCmsDevelopmentRoute = ServicesCmsDevelopmentRouteImport.update({
  id: '/services/cms-development',
  path: '/services/cms-development',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap': typeof SitemapRoute
  '/services/cms-development': typeof ServicesCmsDevelopmentRoute
  '/services/graphic-design': typeof ServicesGraphicDesignRoute
  '/services/it-consultation': typeof ServicesItConsultationRoute
  '/services/seo-geo': typeof ServicesSeoGeoRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap': typeof SitemapRoute
  '/services/cms-development': typeof ServicesCmsDevelopmentRoute
  '/services/graphic-design': typeof ServicesGraphicDesignRoute
  '/services/it-consultation': typeof ServicesItConsultationRoute
  '/services/seo-geo': typeof ServicesSeoGeoRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap': typeof SitemapRoute
  '/services/cms-development': typeof ServicesCmsDevelopmentRoute
  '/services/graphic-design': typeof ServicesGraphicDesignRoute
  '/services/it-consultation': typeof ServicesItConsultationRoute
  '/services/seo-geo': typeof ServicesSeoGeoRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/privacy-policy'
    | '/sitemap'
    | '/services/cms-development'
    | '/services/graphic-design'
    | '/services/it-consultation'
    | '/services/seo-geo'
    | '/services/software-development'
    | '/services/web-development'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/privacy-policy'
    | '/sitemap'
    | '/services/cms-development'
    | '/services/graphic-design'
    | '/services/it-consultation'
    | '/services/seo-geo'
    | '/services/software-development'
    | '/services/web-development'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/privacy-policy'
    | '/sitemap'
    | '/services/cms-development'
    | '/services/graphic-design'
    | '/services/it-consultation'
    | '/services/seo-geo'
    | '/services/software-development'
    | '/services/web-development'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapRoute: typeof SitemapRoute
  ServicesCmsDevelopmentRoute: typeof ServicesCmsDevelopmentRoute
  ServicesGraphicDesignRoute: typeof ServicesGraphicDesignRoute
  ServicesItConsultationRoute: typeof ServicesItConsultationRoute
  ServicesSeoGeoRoute: typeof ServicesSeoGeoRoute
  ServicesSoftwareDevelopmentRoute: typeof ServicesSoftwareDevelopmentRoute
  ServicesWebDevelopmentRoute: typeof ServicesWebDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-development': {
      id: '/services/web-development'
      path: '/services/web-development'
      fullPath: '/services/web-development'
      preLoaderRoute: typeof ServicesWebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/software-development': {
      id: '/services/software-development'
      path: '/services/software-development'
      fullPath: '/services/software-development'
      preLoaderRoute: typeof ServicesSoftwareDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo-geo': {
      id: '/services/seo-geo'
      path: '/services/seo-geo'
      fullPath: '/services/seo-geo'
      preLoaderRoute: typeof ServicesSeoGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/it-consultation': {
      id: '/services/it-consultation'
      path: '/services/it-consultation'
      fullPath: '/services/it-consultation'
      preLoaderRoute: typeof ServicesItConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/graphic-design': {
      id: '/services/graphic-design'
      path: '/services/graphic-design'
      fullPath: '/services/graphic-design'
      preLoaderRoute: typeof ServicesGraphicDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cms-development': {
      id: '/services/cms-development'
      path: '/services/cms-development'
      fullPath: '/services/cms-development'
      preLoaderRoute: typeof ServicesCmsDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapRoute: SitemapRoute,
  ServicesCmsDevelopmentRoute: ServicesCmsDevelopmentRoute,
  ServicesGraphicDesignRoute: ServicesGraphicDesignRoute,
  ServicesItConsultationRoute: ServicesItConsultationRoute,
  ServicesSeoGeoRoute: ServicesSeoGeoRoute,
  ServicesSoftwareDevelopmentRoute: ServicesSoftwareDevelopmentRoute,
  ServicesWebDevelopmentRoute: ServicesWebDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
