/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebcoreSolutionsDubaiRouteImport } from './routes/webcore-solutions-dubai'
import { Route as UaeSoftwareDevelopmentCompanyRouteImport } from './routes/uae-software-development-company'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DubaiWebDevelopmentAgencyRouteImport } from './routes/dubai-web-development-agency'
import { Route as DubaiSeoAgencyRouteImport } from './routes/dubai-seo-agency'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as IndexBackupRouteImport } from './routes/index.backup'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminPagesServicesRouteImport } from './routes/admin.pages.services'
import { Route as AdminPagesHomeRouteImport } from './routes/admin.pages.home'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as AdminPagesServicesIdRouteImport } from './routes/admin.pages.services.$id'

const WebcoreSolutionsDubaiRoute = WebcoreSolutionsDubaiRouteImport.update({
  id: '/webcore-solutions-dubai',
  path: '/webcore-solutions-dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const UaeSoftwareDevelopmentCompanyRoute =
  UaeSoftwareDevelopmentCompanyRouteImport.update({
    id: '/uae-software-development-company',
    path: '/uae-software-development-company',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DubaiWebDevelopmentAgencyRoute =
  DubaiWebDevelopmentAgencyRouteImport.update({
    id: '/dubai-web-development-agency',
    path: '/dubai-web-development-agency',
    getParentRoute: () => rootRouteImport,
  } as any)
const DubaiSeoAgencyRoute = DubaiSeoAgencyRouteImport.update({
  id: '/dubai-seo-agency',
  path: '/dubai-seo-agency',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexBackupRoute = IndexBackupRouteImport.update({
  id: '/index/backup',
  path: '/index/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesServicesRoute = AdminPagesServicesRouteImport.update({
  id: '/pages/services',
  path: '/pages/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesHomeRoute = AdminPagesHomeRouteImport.update({
  id: '/pages/home',
  path: '/pages/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesServicesIdRoute = AdminPagesServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPagesServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dubai-seo-agency': typeof DubaiSeoAgencyRoute
  '/dubai-web-development-agency': typeof DubaiWebDevelopmentAgencyRoute
  '/faqs': typeof FaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap': typeof SitemapRoute
  '/uae-software-development-company': typeof UaeSoftwareDevelopmentCompanyRoute
  '/webcore-solutions-dubai': typeof WebcoreSolutionsDubaiRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/index/backup': typeof IndexBackupRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/pages/home': typeof AdminPagesHomeRoute
  '/admin/pages/services': typeof AdminPagesServicesRouteWithChildren
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/pages/services/$id': typeof AdminPagesServicesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dubai-seo-agency': typeof DubaiSeoAgencyRoute
  '/dubai-web-development-agency': typeof DubaiWebDevelopmentAgencyRoute
  '/faqs': typeof FaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap': typeof SitemapRoute
  '/uae-software-development-company': typeof UaeSoftwareDevelopmentCompanyRoute
  '/webcore-solutions-dubai': typeof WebcoreSolutionsDubaiRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/index/backup': typeof IndexBackupRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/pages/home': typeof AdminPagesHomeRoute
  '/admin/pages/services': typeof AdminPagesServicesRouteWithChildren
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/pages/services/$id': typeof AdminPagesServicesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dubai-seo-agency': typeof DubaiSeoAgencyRoute
  '/dubai-web-development-agency': typeof DubaiWebDevelopmentAgencyRoute
  '/faqs': typeof FaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap': typeof SitemapRoute
  '/uae-software-development-company': typeof UaeSoftwareDevelopmentCompanyRoute
  '/webcore-solutions-dubai': typeof WebcoreSolutionsDubaiRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/index/backup': typeof IndexBackupRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/pages/home': typeof AdminPagesHomeRoute
  '/admin/pages/services': typeof AdminPagesServicesRouteWithChildren
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/pages/services/$id': typeof AdminPagesServicesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dubai-seo-agency'
    | '/dubai-web-development-agency'
    | '/faqs'
    | '/privacy-policy'
    | '/sitemap'
    | '/uae-software-development-company'
    | '/webcore-solutions-dubai'
    | '/admin/login'
    | '/admin/settings'
    | '/blog/$slug'
    | '/index/backup'
    | '/services/$slug'
    | '/admin/'
    | '/blog/'
    | '/services/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/pages/home'
    | '/admin/pages/services'
    | '/admin/blog/'
    | '/admin/pages/services/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dubai-seo-agency'
    | '/dubai-web-development-agency'
    | '/faqs'
    | '/privacy-policy'
    | '/sitemap'
    | '/uae-software-development-company'
    | '/webcore-solutions-dubai'
    | '/admin/login'
    | '/admin/settings'
    | '/blog/$slug'
    | '/index/backup'
    | '/services/$slug'
    | '/admin'
    | '/blog'
    | '/services'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/pages/home'
    | '/admin/pages/services'
    | '/admin/blog'
    | '/admin/pages/services/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dubai-seo-agency'
    | '/dubai-web-development-agency'
    | '/faqs'
    | '/privacy-policy'
    | '/sitemap'
    | '/uae-software-development-company'
    | '/webcore-solutions-dubai'
    | '/admin/login'
    | '/admin/settings'
    | '/blog/$slug'
    | '/index/backup'
    | '/services/$slug'
    | '/admin/'
    | '/blog/'
    | '/services/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/pages/home'
    | '/admin/pages/services'
    | '/admin/blog/'
    | '/admin/pages/services/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DubaiSeoAgencyRoute: typeof DubaiSeoAgencyRoute
  DubaiWebDevelopmentAgencyRoute: typeof DubaiWebDevelopmentAgencyRoute
  FaqsRoute: typeof FaqsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapRoute: typeof SitemapRoute
  UaeSoftwareDevelopmentCompanyRoute: typeof UaeSoftwareDevelopmentCompanyRoute
  WebcoreSolutionsDubaiRoute: typeof WebcoreSolutionsDubaiRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IndexBackupRoute: typeof IndexBackupRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webcore-solutions-dubai': {
      id: '/webcore-solutions-dubai'
      path: '/webcore-solutions-dubai'
      fullPath: '/webcore-solutions-dubai'
      preLoaderRoute: typeof WebcoreSolutionsDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uae-software-development-company': {
      id: '/uae-software-development-company'
      path: '/uae-software-development-company'
      fullPath: '/uae-software-development-company'
      preLoaderRoute: typeof UaeSoftwareDevelopmentCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dubai-web-development-agency': {
      id: '/dubai-web-development-agency'
      path: '/dubai-web-development-agency'
      fullPath: '/dubai-web-development-agency'
      preLoaderRoute: typeof DubaiWebDevelopmentAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dubai-seo-agency': {
      id: '/dubai-seo-agency'
      path: '/dubai-seo-agency'
      fullPath: '/dubai-seo-agency'
      preLoaderRoute: typeof DubaiSeoAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/backup': {
      id: '/index/backup'
      path: '/index/backup'
      fullPath: '/index/backup'
      preLoaderRoute: typeof IndexBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/services': {
      id: '/admin/pages/services'
      path: '/pages/services'
      fullPath: '/admin/pages/services'
      preLoaderRoute: typeof AdminPagesServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/home': {
      id: '/admin/pages/home'
      path: '/pages/home'
      fullPath: '/admin/pages/home'
      preLoaderRoute: typeof AdminPagesHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/services/$id': {
      id: '/admin/pages/services/$id'
      path: '/$id'
      fullPath: '/admin/pages/services/$id'
      preLoaderRoute: typeof AdminPagesServicesIdRouteImport
      parentRoute: typeof AdminPagesServicesRoute
    }
  }
}

interface AdminPagesServicesRouteChildren {
  AdminPagesServicesIdRoute: typeof AdminPagesServicesIdRoute
}

const AdminPagesServicesRouteChildren: AdminPagesServicesRouteChildren = {
  AdminPagesServicesIdRoute: AdminPagesServicesIdRoute,
}

const AdminPagesServicesRouteWithChildren =
  AdminPagesServicesRoute._addFileChildren(AdminPagesServicesRouteChildren)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminPagesHomeRoute: typeof AdminPagesHomeRoute
  AdminPagesServicesRoute: typeof AdminPagesServicesRouteWithChildren
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminPagesHomeRoute: AdminPagesHomeRoute,
  AdminPagesServicesRoute: AdminPagesServicesRouteWithChildren,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DubaiSeoAgencyRoute: DubaiSeoAgencyRoute,
  DubaiWebDevelopmentAgencyRoute: DubaiWebDevelopmentAgencyRoute,
  FaqsRoute: FaqsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapRoute: SitemapRoute,
  UaeSoftwareDevelopmentCompanyRoute: UaeSoftwareDevelopmentCompanyRoute,
  WebcoreSolutionsDubaiRoute: WebcoreSolutionsDubaiRoute,
  BlogSlugRoute: BlogSlugRoute,
  IndexBackupRoute: IndexBackupRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
